name: "Rewritable Pull Request / Issue Comment Action"

branding:
  icon: "message-circle"
  color: "red"

description: "Posts a PR / issue comment that re-writes itself on an update"

inputs:
  message:
    description: "Message that should be printed in the pull request"
    required: true
  github_token:
    description: "Github token of the repository (automatically created by Github)"
    required: true
  comment_identifier:
    description: "A unique identifier for the re-writeable comment (can be the purpose of the comment)"
  issue_id:
    description: "The identifier for a PR / issue that the comment should be made on. Defaults to the PR that the workflow is running on"

outputs:
  comment-id:
    description: "The ID of the newly created / updated comment"

runs:
  using: "node16"
  main: "index.js"
