# This workflow is for use locally using [act](https://github.com/nektos/act).

on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  run-local:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
        # with:
        #   path: "rewritable-pr-comment"
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        name: Set up Node.js
        with:
          node-version: 16

      # Build
      # Build
      - name: "Install dependencies and build"
        run: |
          npm i -g npm@latest
          npm ci
          npm run build
          npm run test
      - name: test action locally
        uses: ./
        with:
          GITHUB_TOKEN: "1234567890"
          message: "this is a really cool sqs message"
          ISSUE_ID: "2"
          COMMENT_IDENTIFIER: "4YE2JbpAewMX4rxmRnWyoSXoAfaiZH19QDB2IR3OSJTxmjSu"
