name: Build, Test, Bump Version and Release
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: write
  issues: write

jobs:
  build-test-publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        name: Set up Node.js
        with:
          node-version-file: ".nvmrc"

      # Cache
      - name: Cache node modules
        id: cache-npm
        continue-on-error: true
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install dependencies
      - name: "Install dependencies and build"
        # if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm i -g npm@latest
          npm ci

      # Build
      - name: "Build"
        run: |
          npm run build
          # npm run test

      # Test
      - uses: ./
        name: "test this action with an issue"
        with:
          debug: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Successfully updated a comment on an issue"
          issue_id: 2
          comment_identifier: "test-output-comment-rewritable-action-ISSUE"

      - uses: ./
        name: "test this action with a PR"
        if: ${{ github.event_name == 'pull_request' }}
        with:
          debug: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Successfully added a comment to a PR"
          comment_identifier: "test-output-comment-rewritable-action-PR"

      # Bump version
      - name: Bump version and push tag
        if: ${{ github.ref == 'refs/heads/main' }} && ${{ github.actor == 'sammcj' }}}
        id: tag_version
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # tag=v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: DISABLED
          pre_release_branches: main # dev

      # Publish
      - name: Create a GitHub release
        if: ${{ github.ref == 'refs/heads/main' }}  && ${{ github.actor == 'sammcj' }}}
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
          allowUpdates: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
